streamline masking from INV2

diff --git a/bin/call_spmmask b/bin/call_spmmask
--- a/bin/call_spmmask
+++ b/bin/call_spmmask
@@ -19,15 +19,16 @@ myGRE_BrainMask, which should be located in the data-folder.
 Args:
  -s <SPM_PATH>  path to SPM; should contain CAT12 in toolbox directory
  -l <LOG_PATH>	path to working directory, defaults to DIR_LOGS
+ --clean        remove intermediate files
  <input image>  input image. Can either be *.nii.gz or *.nii image. In the case of the former,
                 new *.nii-file will be created alongside of the *.nii.gz file, as SPM does
                 not like *.nii.gz files.
  <output image>	name of output image, including directory
- <delete tmp> 	delete intermediate files (yes/y|no/n)
 
 Usage:
- call_spmmask inv2.nii.gz mask_inv2 y
-
+  call_spmmask inv2.nii.gz mask_inv2.nii.gz
+  call_spmmask --clean inv2.nii.gz mask_inv2.nii.gz
+  
 ---------------------------------------------------------------------------------------------------
 
 USAGE
@@ -40,9 +41,23 @@ if [[ $# -lt 1 ]] ; then
 fi
 
 # Check for subject & session flags
-while getopts l:s: argument
+CLEAN_UP=0
+while getopts :-:l:s: argument
 do
   case ${argument} in
+    -)
+      case "${OPTARG}" in     
+        clean)
+          CLEAN_UP=1
+          ;;        
+        *)
+          if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then
+            Usage >&2
+            echo "Unknown option --${OPTARG}"
+            exit 1
+          fi
+          ;;
+      esac;;   
     l)  LOG=${OPTARG}
             ;;
     s)  SPM=${OPTARG}
@@ -52,7 +67,6 @@ done
 
 INPUT=${@:$OPTIND:1}
 OUTPUT=${@:$OPTIND+1:1}
-RM=${@:$OPTIND+2:1}
 
 #-----------------------------------------------------------------------------
 # Get bash helper functions
@@ -99,6 +113,7 @@ fi
 
 # if file specified is in current directory, add entire path
 in_file=`fetch_filepath ${in_file}`
+out_file=`fetch_filepath ${OUTPUT}`
 
 #-----------------------------------------------------------------------------
 # Create new script
@@ -107,8 +122,8 @@ if [[ -f ${new_script} ]]; then
   rm -r ${new_script}
 fi
 
-if [[ ! -d $(dirname ${OUTPUT}) ]]; then
-  mkdir -p $(dirname ${OUTPUT})
+if [[ ! -d $(dirname ${out_file}) ]]; then
+  mkdir -p $(dirname ${out_file})
 fi
 
 make_mask_script ${SPM_PATH} ${in_file} ${new_script}
@@ -121,22 +136,28 @@ if [[ $? -ne 0 ]]; then
   exit 1
 fi
 
-if [[ ${RM} == "y" ]]; then
-  rm -r $(dirname ${in_file})/c*$(basename ${in_file}) *.mat 2>/dev/null
-fi
-
 # Convert SPM's .nii-files to .nii.gz if the input file was nii.gz
 if [[ ${ext} == "gz" ]]; then
   mask_img=`find $(dirname ${in_file}) -type f -name "mask_$(basename ${in_file})*" 2>/dev/null`
   if [[ ! -z ${mask_img} ]]; then
-    gzip -c ${mask_img} > ${OUTPUT} 2>/dev/null
+    gzip -c ${mask_img} > ${out_file} 2>/dev/null
 
     # set qformcode to 1 (prefered by nighres)
-    if [[ `fslval ${OUTPUT} qform_code` -ne 1 ]]; then
-        fslorient -setqformcode 1 ${OUTPUT}
+    if [[ `fslval ${out_file} qform_code` -ne 1 ]]; then
+        fslorient -setqformcode 1 ${out_file}
     fi
   fi
   rm -r ${in_file}
 else
-  mv ${mask_img} $(dirname ${OUTPUT})
+  mv ${mask_img} $(dirname ${out_file})
+
+  # keep temp files if something went wrong
+  if [[ $? -ne 0 ]]; then
+    CLEAN_UP=0
+  fi
+fi
+
+# clean up files
+if [[ ${CLEAN_UP} -eq 1 ]]; then
+  rm -r $(dirname ${in_file})/c*$(basename ${in_file}) *.mat 2>/dev/null
 fi
