expert options for FreeSurfer + other extras

diff --git a/bin/call_freesurfer b/bin/call_freesurfer
--- a/bin/call_freesurfer
+++ b/bin/call_freesurfer
@@ -3,6 +3,7 @@
 #---------------------------------------------------------------------------------------------------------
 # check if there's is a setup file containing the major paths and source it if it exists
 call_loadsetup
+source call_bashhelper
 
 #---------------------------------------------------------------------------------------------------------
 # Create help text
@@ -25,12 +26,9 @@ Usage:
                   -e <edit type> -o <other editing options> [other options]
 Args:
   -s <subj ID>        subject ID as per output of FreeSurfer (e.g., 'sub-001')
-
   -t <t1 input>       T1-weighted image (not necessary if you're running debugging mode)
-
   -p <t2 input>       T2-weighted image (not necessary, but recommended for better pial-surface
                       segmentation
-
   -r <recon stage>    Which stage of recon-all should be run; combinations are possible!
                       Possible options are:
                         'all' = all stages (Perform all reconstruction steps, including
@@ -42,23 +40,22 @@ Args:
                         '12'  = autorecon1 and autorecon2 (do your edits after this step)
                         '23'  = autorecon2 and autorecon3 (perform any edits and re-run with
                                 '-e flag')
-
   -e <edit type>      What type of edit did you perform after autorecon2?
                       Possible options are:
                         'cp'  = you made normalization edits  > runs -autorecon2-cp
                         'wm'  = you made white matter edits   > runs -autorecon2-wm
                         'pial'= you made pial edits           > runs -autorecon-pial
-
   -o <other editing>  Here you can specify the gcut-option to remove latched on pial surface
-
-
-  -v <version>        FreeSurfer version if multiple are available. Note that fMRIprep only 
-                      uses 6.0.0, which is a bit worse at dealing with T2-images.
+  -x <expert opts>    expert option file that maps to '-expert'. 
   --freeview          Open FreeView automatically (default is NO!)
   --force_exec        Force execution even though directory exists already
   --sge               Submit the script to a cluster using a template script
   --local             Force local processing even though cluster is available
   --no_highres        Turn of highres mode by setting '-highres' flag empty
+  --xopts-use         maps to '-xopts-use' for existing expert option file; use existing file
+  --xopts-clean       maps to '-xopts-clean' for existing expert option file; delete existing 
+                      file
+  --xopts-overwrite   maps to '-xopts-overwrite' for existing expert option file; use new file
 
 Instructions for editing (from Andrew Jahn's YouTube series):
   - Control points (intensity normalization errors):
@@ -68,10 +65,10 @@ Instructions for editing (from Andrew Jahn's YouTube series):
 
     1.) Open freeview with 'call_freeview <subj ID> surf 0'
     2.) Find slices where the problems begins and starts (easiest in axial view)
-    3.) To add control points, click 'File'>'New point set'>name it 'control.dat'>select 'brainmask.mgz'
-        as tempalte
-    4.) Left-click voxels that are white matter but not included in the WM-boundary. Space out control
-        points by a few mm
+    3.) To add control points, click 'File'>'New point set'>name it 'control.dat'>select 'brain-
+        mask.mgz' as tempalte
+    4.) Left-click voxels that are white matter but not included in the WM-boundary. Space out 
+        control points by a few mm
     5.) When you're done, click on 'File'>'Save Point Set as'>'control.dat' in the 'tmp'-folder
     6.) Re-run with call_freesurfer -s sub-001 -r 23 -e cp
 
@@ -81,17 +78,19 @@ Instructions for editing (from Andrew Jahn's YouTube series):
     1.) Make a back-up of the directory
     2.) Run call_freesurfer -s <subj ID> -o gcut
     3.) This outputs a file called brainmask.gcut.mgz
-    4.) If this has fixed the problem, run call_freesurfer -s <subj ID> -r 23 (leave '-e' empty so we
-        know you did gcut)
+    4.) If this has fixed the problem, run call_freesurfer -s <subj ID> -r 23 (leave '-e' empty so 
+        we know you did gcut)
 
   - Pial edits:
-    If the above strategy was not successful, you can try more aggressive skullstripping, but this u
-    sually does more harm than good. In that case, pial-edits are recommended.
+    If the above strategy was not successful, you can try more aggressive skullstripping, but this 
+    usually does more harm than good. In that case, pial-edits are recommended.
 
     1.) Open freeview with 'call_freeview <subj ID> surf 0'
-    2.) Make sure 'brainmask.mgz' is highlighted, and press 'recon-edit' icon (head with 'R' and pencil)
+    2.) Make sure 'brainmask.mgz' is highlighted, and press 'recon-edit' icon (head with 'R' and 
+        pencil)
     3.) To remove voxels, pressing 'shift'+left mouse
-    4.) Find slices where the problems begins and starts (easiest in axial view). Be conservative though!
+    4.) Find slices where the problems begins and starts (easiest in axial view). Be conservative 
+        though!
     5.) When you're done, press 'File'>'Save Volume'
     6.) Re-run with call_freesurfer -s sub-001 -r 23 -e pial
 
@@ -104,10 +103,15 @@ Example (TL;DR):
   After pial edits:       call_freesurfer -s <subj ID> -r 23 -e pial
   Include T2 after FS v6: call_freesurfer -s <subj ID> -r 23 -e wm -p <T2 image>
 
+Notes:
+  When an expert options is passed, it will be copied to scripts/expert-options. Future calls to 
+  recon-all, the user MUST explicitly specify how to treat this file. Options are (1) use the file 
+  ('--xopts-use'), or (2) delete it ('--xopts-clean'). If this file exsts and the user specifies 
+  another expert options file, then the user must also specify '--xopts-overwrite'.
+
 ---------------------------------------------------------------------------------------------------
 
 USAGE
-    exit 1
 }
 
 #-----------------------------------------------------------------------------
@@ -115,8 +119,10 @@ USAGE
 FREEVIEW=0
 FORCE_EXEC=0
 SGE=""
-NO_HIGHRES="-hires"
-while getopts :-:hs:t:p:r:e:o:f:c:v: arg
+highres_flag="-hires"
+XOPTS_=""
+EXPERT_FILE=""
+while getopts :-:hs:t:p:r:e:o:f:c:x: arg
 do
   case ${arg} in
     -)
@@ -134,13 +140,21 @@ do
           SGE="LOCAL"
           ;;   
         no_highres)
-          NO_HIGHRES=""
-          ;;                                                      
+          highres_flag=""
+          ;;             
+        xopts-use)
+          XOPTS_="-xopts-use"
+          ;;             
+        xopts-clean)
+          XOPTS_="-xopts-clean"
+          ;;               
+        xopts-overwrite)
+          XOPTS_="-xopts-overwrite"
+          ;;              
         *)
           if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then
-            echo "Unknown option --${OPTARG}, possible options are:"
-            for ii in ${opts[@]}; do echo " ${ii}"; done
-            echo "Enter \"`basename ${0}`\" what these flags do"
+            Usage >&2
+            echo "Unknown option --${OPTARG}"
             exit 1
           fi
           ;;
@@ -157,8 +171,8 @@ do
           ;;
     o)  option=${OPTARG}
           ;;
-    v)  VERSION=${OPTARG}
-          ;;            
+    x)  EXPERT_FILE=${OPTARG}
+          ;;                      
   esac
 done
 
@@ -186,6 +200,31 @@ if [[ -z ${SGE} ]]; then
   fi
 fi
 
+# check if we got expert file
+if [[ ! -z ${EXPERT_FILE} ]]; then
+  if [[ ! -f ${EXPERT_FILE} ]]; then
+    echo "ERROR in `basename ${0}`: specified expert file \"${EXPERT_FILE}\" does not exist"
+    exit 1
+  fi
+  expert_flag="-expert ${EXPERT_FILE}"
+  echo "Expert options: \"${EXPERT_FILE}\""
+
+  # check if there's an expert-options file already and whether the user has specified a protocol
+  if [[ -f ${SUBJECTS_DIR}/${subj_ID}/scripts/expert-options ]]; then
+    if [[ -z ${XOPTS_} ]]; then
+      echo "ERROR in `basename ${0}`: an expert-options file was specified, but one already exists."
+      echo "Please specify the protocol to deal with this with one of the following flags:"
+      echo "  1) --xopts-use;       use the existing file"
+      echo "  2) --xopts-clean;     delete the existing file"
+      echo "  3) --xopts-overwrite; use a new file"
+      exit 1
+    fi
+  fi
+else
+  XOPTS_=""
+  expert_flag=""
+fi
+
 #-----------------------------------------------------------------------------
 # Create function that submits or runs stuff locally
 CMD(){
@@ -198,65 +237,64 @@ CMD(){
 
   if [[ ${SGE} == "SGE" ]]; then
     echo "Submitting job to cluster"
+    parallel_flag="-parallel"
+    mp_flag="-openmp 12"
+    submit=1
+  else
+    parallel_flag=""
+    mp_flag=""
+    submit=0
+  fi
 
-    # delete previously existing file
-    fs_script=${PATH_HOME}/freesurfer/${1}_${2}.sh
-    if [[ -f ${fs_script} ]]; then
-      rm -r ${fs_script}
-    fi
+  # delete previously existing file
+  fs_script=${PATH_HOME}/freesurfer/${PROJECT}/${1}_${2}.sh
+  echo $fs_script
+  if [[ -f ${fs_script} ]]; then
+    rm -r ${fs_script}
+  fi
 
-    # bash will complain if you want to create a file but the directory doesn't exist
-    if [[ ! -d $(dirname ${fs_script}) ]]; then
-      mkdir -p $(dirname ${fs_script})
-    fi
+  # bash will complain if you want to create a file but the directory doesn't exist
+  if [[ ! -d $(dirname ${fs_script}) ]]; then
+    mkdir -p $(dirname ${fs_script})
+  fi
 
-    # remove old log file
-    if [ -f $(dirname ${fs_script})/$(basename ${fs_script} .sh).log ]; then
-      rm $(dirname ${fs_script})/$(basename ${fs_script} .sh).log
-    fi 
+  # remove old log file
+  if [ -f $(dirname ${fs_script})/$(basename ${fs_script} .sh).log ]; then
+    rm $(dirname ${fs_script})/$(basename ${fs_script} .sh).log
+  fi 
 
-    # If you have ran FreeSurfer in fMRIprep, fsaverage will miss a few labels that
-    # FreeSurfer v7 has. Hence, we need to specify that we want to use version 6,
-    # otherwise it will throw errors
+  # If you have ran FreeSurfer in fMRIprep, fsaverage will miss a few labels that
+  # FreeSurfer v7 has.
 
-    if [[ ! -z ${VERSION} ]]; then
-      version=${VERSION}
-    else
-      version="7.2.0"
-    fi
+  # check if function exists, will throw an error if it doesn't exist
+  fn_exists freesurfer
+  echo "Using FreeSurfer from: `which freesurfer`"
 
-    echo "Using FreeSurfer version: ${version}"
-
-    # echo "${SUBJECTS_DIR}"
-    (
-    echo "#!/bin/bash"
-    echo "#$ -S /bin/bash"
-    echo "#$ -N $(basename ${fs_script} .sh)"
-    echo "#$ -wd ${SUBJECTS_DIR}"
-    echo "#$ -o $(dirname ${fs_script})/$(basename ${fs_script} .sh).log"
-    echo "#$ -j Y"
-    echo "#$ -q ${SGE_QUEUE_LONG}"
-    echo "#$ -V"
-    echo ""
-    echo "module load freesurfer/${version}"
-    echo "export FREESURFER=/packages/freesurfer/${version}"
-    echo "export SUBJECTS_DIR=${SUBJECTS_DIR}"
-    echo "recon-all -subjid ${1} ${4} ${NO_HIGHRES} -parallel -openmp 12 ${3} ${5}"
-    ) > ${fs_script}
-    
+  # echo "${SUBJECTS_DIR}"
+  (
+  echo "#!/bin/bash"
+  echo "#$ -S /bin/bash"
+  echo "#$ -N $(basename ${fs_script} .sh)"
+  echo "#$ -wd ${SUBJECTS_DIR}"
+  echo "#$ -o $(dirname ${fs_script})/$(basename ${fs_script} .sh).log"
+  echo "#$ -j Y"
+  echo "#$ -q ${SGE_QUEUE_LONG}"
+  echo "#$ -V"
+  echo ""
+  echo "export SUBJECTS_DIR=${SUBJECTS_DIR}"
+  echo "recon-all -subjid ${1} ${4} ${highres_flag} ${parallel_flag} ${mp_flag} ${3} ${5} ${expert_flag} ${XOPTS_}"
+  ) > ${fs_script}
+  
+  if [[ ${submit} -eq 1 ]]; then
     qsub ${fs_script}
-
     echo "Now wait until the program has finished and do some editing in FreeView if required."
     echo "Waiting to qstat.."
     sleep 5
     qstat
-
   else
-
     echo "Running FreeSurfer locally"
-    recon-all -subjid ${1} ${4} ${NO_HIGHRES} ${3} ${5}
+    bash ${fs_script}
     echo "Now do some editing in FreeView if required."
-
   fi
 
 }
diff --git a/shell/spinoza_freesurfer b/shell/spinoza_freesurfer
--- a/shell/spinoza_freesurfer
+++ b/shell/spinoza_freesurfer
@@ -18,10 +18,19 @@ stage we should run (default is 'all'), and where to look for a T2w-image if the
 Usage:
   spinoza_freesurfer [options] <directory with anats> <stage> <T2-directory>
 
-Arguments:
+Flagged arguments:
   -s <subject>        subject ID (e.g., 01). Can also be comma-separated list: 01,02,05
   -n <session>        session ID (e.g., 1, 2, or n)
-  -o                  overwrite existing files
+  -o|--ow             overwrite existing files
+  -x <file>           use expert file
+  --sge               Submit the script to a cluster using a template script
+  --local             Force local processing even though cluster is available
+  --no_highres        Turn of highres mode by setting '-highres' flag empty
+  --xopts-use         maps to '-xopts-use' for existing expert option file; use existing file
+  --xopts-clean       maps to '-xopts-clean' for existing expert option file; delete existing file
+  --xopts-overwrite   maps to '-xopts-overwrite' for existing expert option file; use new file
+
+Positional arguments:
   <anat folder>       folder containing the T1w-file. In 'master', we'll look through various fol-
                       ders. In order of priority:
                         -'<derivatives>/masked_${DATA,,}'
@@ -39,42 +48,90 @@ General approach for segmentation:
   - Fix skullstrip:   call_freesurfer -s <subj ID> -o gcut                    ~10 minutes
   - Run autorecon2:   call_freesurfer -s <subj ID> -r 2                       ~few hours
   - Fix errors with:
-      - norm; then run call_freesurfer -s ${SUBJECT_PREFIX}001 -r 23 -e cp                 ~few hours
-      - pia;  then run call_freesurfer -s ${SUBJECT_PREFIX}001 -r 23 -e pial               ~few hours
+      - norm; then run call_freesurfer -s ${SUBJECT_PREFIX}001 -r 23 -e cp    ~few hours
+      - pia;  then run call_freesurfer -s ${SUBJECT_PREFIX}001 -r 23 -e pial  ~few hours
 
 You can specify in which directory to look for anatomical scans in the first argument. Usually,
-this is one of the following options: DIR_DATA_HOME if we should use the T1w in the project/${SUBJECT_PREFIX}xxx
-/anat directory, or DIR_DATA_DERIV/pymp2rage to use T1w-images derived from pymp2rage, or DIR_DATA_
-DERIV/masked_mp2rage to use T1w-images where the dura and sagittal sinus are masked out (should be
-default!). In any case, it assumes that the file is in YOURINPUT/${SUBJECT_PREFIX}xxx/ses-1/. If the input is
-equal to the DIR_DATA_HOME variable, this will be recognize and 'anat' will be appended to YOURINPUT
-/${SUBJECT_PREFIX}xxx/ses-1/anat.
+this is one of the following options: DIR_DATA_HOME if we should use the T1w in the project/
+${SUBJECT_PREFIX}xxx/anat directory, or DIR_DATA_DERIV/pymp2rage to use T1w-images derived from 
+pymp2rage, or DIR_DATA_DERIV/masked_mp2rage to use T1w-images where the dura and sagittal sinus 
+are masked out (should be default!). In any case, it assumes that the file is in YOURINPUT/
+${SUBJECT_PREFIX}xxx/ses-1/. If the input is equal to the DIR_DATA_HOME variable, this will 
+be recognize and 'anat' will be appended to YOURINPUT/${SUBJECT_PREFIX}xxx/ses-1/anat.
 
 You can also specify a directory where the T2-weighted image is located. Do this the same way as de-
-scribed above. To you path, ${SUBJECT_PREFIX}xxx/ses-x will be appended if the input path is not equal to DIR_DATA
-_HOME. Again, if it is, ${SUBJECT_PREFIX}xxx/ses-x/anat will be appended as well.
+scribed above. To you path, ${SUBJECT_PREFIX}xxx/ses-x will be appended if the input path is not 
+equal to DIR_DATA_HOME. Again, if it is, ${SUBJECT_PREFIX}xxx/ses-x/anat will be appended as well.
 
 Example:
   spinoza_freesurfer DIR_DATA_DERIV/masked_mp2rage all DIR_DATA_HOME
   spinoza_freesurfer -s 001 -n 1 DIR_DATA_ANAT all DIR_DATA_HOME
 
+Notes:
+  When an expert options is passed, it will be copied to scripts/expert-options. Future calls to 
+  recon-all, the user MUST explicitly specify how to treat this file. Options are (1) use the file 
+  ('--xopts-use'), or (2) delete it ('--xopts-clean'). If this file exsts and the user specifies 
+  another expert options file, then the user must also specify '--xopts-overwrite'.
+
 ---------------------------------------------------------------------------------------------------
 
 USAGE
-    exit 1
 }
 
 # Check for subject & session flags
 OW=0
-while getopts os:n: argument
+freeview_flag=""
+highres_flag=""
+sge_flag=""
+expert_flag=""
+while getopts :-:os:n:x: argument
 do
   case ${argument} in
+    -)
+      case "${OPTARG}" in     
+        freeview)
+          FREEVIEW=1
+          ;;            
+        force_exec)
+          FORCE_EXEC=1
+          ;;          
+        sge)
+          sge_flag="--sge"
+          ;;        
+        local)
+          sge_flag="--local"
+          ;;   
+        ow)
+          OW=1
+          ;;          
+        no_highres)
+          highres_flag="--no_highres"
+          ;;             
+        xopts-use)
+          XOPTS_="--xopts-use"
+          ;;             
+        xopts-clean)
+          XOPTS_="--xopts-clean"
+          ;;               
+        xopts-overwrite)
+          XOPTS_="--xopts-overwrite"
+          ;;                                                                                     
+        *)
+          if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then
+            Usage >&2
+            echo "Unknown option --${OPTARG}"
+            exit 1
+          fi
+          ;;
+      esac;;   
     s)  sub=${OPTARG}
           ;;
     n)  ses=${OPTARG}
           ;;
     o)  OW=1
-          ;;          
+          ;; 
+    x)  EXPERT_FILE=${OPTARG}
+          ;;           
   esac
 done
 
@@ -95,6 +152,18 @@ else
   IFS=', ' read -r -a search <<< "${sub}"
   search=${search[@]}
   unset IFS
+fi
+
+# check if we got expert file
+if [[ ! -z ${EXPERT_FILE} ]]; then
+  if [[ ! -f ${EXPERT_FILE} ]]; then
+    echo "ERROR in `basename ${0}`: specified expert file \"${EXPERT_FILE}\" does not exist"
+    exit 1
+  fi
+  expert_flag="-x ${EXPERT_FILE}"
+else
+  XOPTS_=""
+  expert_flag=""
 fi
 
 #-----------------------------------------------------------------------------
@@ -155,7 +224,18 @@ for subID in ${search}; do
   # run if input exists
   if [[ ! -z ${input_t1w} ]]; then
 
-    if [[ ! -d ${SUBJECTS_DIR}/${sub_name} ]]; then
+    # execute either when there's no directory, or when there's no files in /surf
+    execute=0
+    if [[ -d ${SUBJECTS_DIR}/${sub_name} ]]; then
+      nr_files=`ls -l ${SUBJECTS_DIR}/${sub_name}/surf | grep "total" | cut -d' ' -f2`
+      if [ ${nr_files} -eq 0 ]; then
+        execute=1
+      fi
+    else
+      execute=1
+    fi
+
+    if [[ ${execute} -eq 1 ]]; then
 
       echo
       echo "**************************************** Processing ${sub_name} ***************************************"
@@ -179,6 +259,7 @@ for subID in ${search}; do
               echo 
               exit 1
             elif [ ${ct} -eq 1 ]; then
+              echo "Including T2w: \"${input_t2w}\""
               T2_flag="-p ${input_t2w}"
             else
               echo "ERROR in `basename ${0}`: not sure what went wrong.."
@@ -196,17 +277,23 @@ for subID in ${search}; do
       fi
 
       # cmd
-      call_freesurfer -s ${sub_name} -t ${input_t1w} -r ${STAGE} ${T2_flag} -v \"7.2.0\"
+      call_freesurfer \
+        -s ${sub_name} \
+        -t ${input_t1w} \
+        -r ${STAGE} \
+        ${T2_flag} \
+        ${highres_flag} \
+        ${expert_flag} \
+        ${XOPTS_} \
+        ${sge_flag}
 
     else
       echo "${sub_name}: FreeSurfer already ran"
     fi
 
   else
-
-    echo "No T1-weighted image found"
+    echo "No T1-weighted image found in \"${T1_DIR}\""
     continue
-
   fi
 
 done
