more indentation

diff --git a/bin/call_spmphysio b/bin/call_spmphysio
--- a/bin/call_spmphysio
+++ b/bin/call_spmphysio
@@ -8,7 +8,7 @@
 #---------------------------------------------------------------------------------------------------------
 # Create help text
 function Usage {
-		cat <<USAGE
+    cat <<USAGE
 
 ---------------------------------------------------------------------------------------------------
 call_spmphysio
@@ -34,12 +34,12 @@ Usage:
 ---------------------------------------------------------------------------------------------------
 
 USAGE
-		exit 1
+    exit 1
 }
 
 if [[ $# -lt 1 ]] ; then
-	Usage >&2
-	exit 1
+  Usage >&2
+  exit 1
 fi
 
 # Check for subject & session flags
@@ -67,14 +67,14 @@ source call_bashhelper
 #-----------------------------------------------------------------------------
 # Define default SPM-path
 if [[ -z ${SPM} ]]; then
-	if [[ -z ${SPM_PATH} ]]; then
-		echo "ERROR: SPM_PATH-variable is empty. Either define it, or specify an SPM-path with \"-s <path/to/spm>\""
-		exit 1
-	else
-		SPM_PATH=${SPM_PATH}
-	fi
+  if [[ -z ${SPM_PATH} ]]; then
+    echo "ERROR: SPM_PATH-variable is empty. Either define it, or specify an SPM-path with \"-s <path/to/spm>\""
+    exit 1
+  else
+    SPM_PATH=${SPM_PATH}
+  fi
 else
-	SPM_PATH=${SPM}
+  SPM_PATH=${SPM}
 fi
 
 #-----------------------------------------------------------------------------
@@ -108,11 +108,11 @@ fi
 # Create new script
 new_script=$(dirname ${OUTPUT})/spm_physio.m
 if [[ -f ${new_script} ]]; then
-	rm -r ${new_script}
+  rm -r ${new_script}
 fi
 
 if [[ ! -d $(dirname ${OUTPUT}) ]]; then
-	mkdir -p $(dirname ${OUTPUT})
+  mkdir -p $(dirname ${OUTPUT})
 fi
 
 make_physio_script ${SPM_PATH} ${INPUT} ${TR} ${VOLS} ${OUTPUT} ${new_script}
@@ -121,6 +121,6 @@ make_physio_script ${SPM_PATH} ${INPUT} ${TR} ${VOLS} ${OUTPUT} ${new_script}
 call_matlab ${new_script}
 
 if [[ $? -ne 0 ]]; then
-    echo "ERROR: matlab exited with non-zero status"
-    exit 1
+  echo "ERROR: matlab exited with non-zero status"
+  exit 1
 fi
diff --git a/bin/call_spmsuit b/bin/call_spmsuit
--- a/bin/call_spmsuit
+++ b/bin/call_spmsuit
@@ -8,7 +8,7 @@
 #---------------------------------------------------------------------------------------------------------
 # Create help text
 function Usage {
-		cat <<USAGE
+    cat <<USAGE
 
 ---------------------------------------------------------------------------------------------------
 call_spmsuit
@@ -24,7 +24,7 @@ Args:
                 new *.nii-file will be created alongside of the *.nii.gz file, as SPM does
                 not like *.nii.gz files.
  <output base>	basename of output image, including directory, '_desc-cereb_mask.nii[.gz]', '_desc-
-								cereb-wm.nii[.gz]', and '_desc-cereb_gm.nii[.gz]' will be appended
+                                cereb-wm.nii[.gz]', and '_desc-cereb_gm.nii[.gz]' will be appended
 
 Usage:
  call_spmsuit t1w.nii.gz <project>/derivatives/suit/<subject>/<ses>/<subject>
@@ -32,12 +32,12 @@ Usage:
 ---------------------------------------------------------------------------------------------------
 
 USAGE
-		exit 1
+    exit 1
 }
 
 if [[ $# -lt 1 ]] ; then
-	Usage >&2
-	exit 1
+  Usage >&2
+  exit 1
 fi
 
 # Check for subject & session flags
@@ -61,14 +61,14 @@ OUTPUT=${@:$OPTIND+1:1}
 #-----------------------------------------------------------------------------
 # Define default SPM-path
 if [[ -z ${SPM} ]]; then
-	if [[ -z ${SPM_PATH} ]]; then
-		echo "ERROR: SPM_PATH-variable is empty. Either define it, or specify an SPM-path with \"-s <path/to/spm>\""
-		exit 1
-	else
-		SPM_PATH=${SPM_PATH}
-	fi
+  if [[ -z ${SPM_PATH} ]]; then
+    echo "ERROR: SPM_PATH-variable is empty. Either define it, or specify an SPM-path with \"-s <path/to/spm>\""
+    exit 1
+  else
+    SPM_PATH=${SPM_PATH}
+  fi
 else
-	SPM_PATH=${SPM}
+  SPM_PATH=${SPM}
 fi
 
 #-----------------------------------------------------------------------------
@@ -81,21 +81,21 @@ OUTPUT=`fetch_filepath ${OUTPUT}`
 
 ext=`fetch_extension ${INPUT}`
 if [[ ${ext} == "gz" ]]; then
-	in_file=$(dirname ${INPUT})/$(basename ${INPUT} .gz)
-	gunzip -c ${INPUT} > ${in_file}
+  in_file=$(dirname ${INPUT})/$(basename ${INPUT} .gz)
+  gunzip -c ${INPUT} > ${in_file}
 else
-	in_file=${INPUT}
+  in_file=${INPUT}
 fi
 
 #-----------------------------------------------------------------------------
 # Create new script
 new_script=$(dirname ${OUTPUT})/spm_suit.m
 if [[ -f ${new_script} ]]; then
-	rm -r ${new_script}
+  rm -r ${new_script}
 fi
 
 if [[ ! -d $(dirname ${OUTPUT}) ]]; then
-	mkdir -p $(dirname ${OUTPUT})
+  mkdir -p $(dirname ${OUTPUT})
 fi
 
 make_suit_script ${SPM_PATH} ${in_file} ${new_script}
@@ -104,8 +104,8 @@ make_suit_script ${SPM_PATH} ${in_file} ${new_script}
 call_matlab ${new_script}
 
 if [[ $? -ne 0 ]]; then
-	echo "ERROR: matlab exited with non-zero status"
-	exit 1
+  echo "ERROR: matlab exited with non-zero status"
+  exit 1
 fi
 
 # Convert SPM's .nii-files to .nii.gz if the input file was nii.gz
@@ -115,18 +115,18 @@ wm_img=`find $(dirname ${in_file}) -type f -name "*seg2*" 2>/dev/null`
 if [[ ! -z ${mask_img} ]]; then
   if [[ ${ext} == "gz" ]]; then
     gzip -c ${mask_img} > ${OUTPUT}_desc-cereb_mask.nii.gz 2>/dev/null
-		gzip -c ${wm_img} > ${OUTPUT}_desc-cereb_wm.nii.gz 2>/dev/null
-		gzip -c ${gm_img} > ${OUTPUT}_desc-cereb_gm.nii.gz 2>/dev/null
+    gzip -c ${wm_img} > ${OUTPUT}_desc-cereb_wm.nii.gz 2>/dev/null
+    gzip -c ${gm_img} > ${OUTPUT}_desc-cereb_gm.nii.gz 2>/dev/null
 
-		rm -r ${in_file} ${mask_img} ${wm_img} ${gm_img} 2>/dev/null
+    rm -r ${in_file} ${mask_img} ${wm_img} ${gm_img} 2>/dev/null
   else
     mv ${mask_img} ${OUTPUT}_desc-cereb_mask.nii
-		mv ${wm_img} ${OUTPUT}_desc-cereb_wm.nii
-		mv ${gm_img} ${OUTPUT}_desc-cereb_gm.nii
+    mv ${wm_img} ${OUTPUT}_desc-cereb_wm.nii
+    mv ${gm_img} ${OUTPUT}_desc-cereb_gm.nii
   fi
 fi
 
 if [[ ${RM} -eq 1 ]]; then
-	rm -r $(dirname ${in_file})/c*$(basename ${in_file}) *.mat 2>/dev/null
-	rm -r $(dirname ${in_file})/y_$(basename ${in_file}) 2>/dev/null
+  rm -r $(dirname ${in_file})/c*$(basename ${in_file}) *.mat 2>/dev/null
+  rm -r $(dirname ${in_file})/y_$(basename ${in_file}) 2>/dev/null
 fi 
