uncomment actual call to fmriprep

diff --git a/bin/call_fmriprep b/bin/call_fmriprep
--- a/bin/call_fmriprep
+++ b/bin/call_fmriprep
@@ -197,109 +197,109 @@ fi
 
 #-----------------------------------------------------------------------------
 #Run fmriprep
-# if [ ${system} == "SGE" ]; then
+if [ ${system} == "SGE" ]; then
 
-#   nthreads=15
-#   #-----------------------------------------------------------------------------
-#   # Set default binding point if none specified
-#   if [[ -z ${BIND} ]]; then
-#     binding=${PATH_HOME}
-#   else
-#     binding=${BIND}
-#   fi
+  nthreads=15
+  #-----------------------------------------------------------------------------
+  # Set default binding point if none specified
+  if [[ -z ${BIND} ]]; then
+    binding=${PATH_HOME}
+  else
+    binding=${BIND}
+  fi
 
-#   #-----------------------------------------------------------------------------
-#   # Set default container if none specified
-#   if [[ -z ${IMG} ]]; then
-#     fprep_container=${FPREP_SIMG}
-#   else
-#     fprep_container=${IMG}
-#   fi
+  #-----------------------------------------------------------------------------
+  # Set default container if none specified
+  if [[ -z ${IMG} ]]; then
+    fprep_container=${FPREP_SIMG}
+  else
+    fprep_container=${IMG}
+  fi
 
-#   if [[ ! -f ${fprep_container} ]]; then
-#     echo "Could not find singularity image \"${fprep_container}\" for fmriprep.."
-#     exit 1
-#   fi
+  if [[ ! -f ${fprep_container} ]]; then
+    echo "Could not find singularity image \"${fprep_container}\" for fmriprep.."
+    exit 1
+  fi
 
-#   if [[ ${mode} == "anat" ]]; then
+  if [[ ${mode} == "anat" ]]; then
 
-#     unset PYTHONPATH; singularity run --cleanenv -B ${binding}:${binding} ${fprep_container} \
-#       ${project} ${derivatives} \
-#       participant \
-#       --participant-label ${subj_ID} \
-#       --skip-bids-validation \
-#       --md-only-boilerplate \
-#       --fs-license-file ${license} \
-#       --output-spaces ${FPREP_OUT_SPACES} \
-#       ${cifti_flag} \
-#       --anat-only \
-#       --nthreads ${nthreads} \
-#       --bids-filter-file ${CONFIG} \
-#       --stop-on-first-crash \
-#       -w ${work}
+    unset PYTHONPATH; singularity run --cleanenv -B ${binding}:${binding} ${fprep_container} \
+      ${project} ${derivatives} \
+      participant \
+      --participant-label ${subj_ID} \
+      --skip-bids-validation \
+      --md-only-boilerplate \
+      --fs-license-file ${license} \
+      --output-spaces ${FPREP_OUT_SPACES} \
+      ${cifti_flag} \
+      --anat-only \
+      --nthreads ${nthreads} \
+      --bids-filter-file ${CONFIG} \
+      --stop-on-first-crash \
+      -w ${work}
 
-#   else
+  else
 
-#     unset PYTHONPATH; singularity run --cleanenv -B ${binding}:${binding} ${fprep_container} \
-#       ${project} ${derivatives} \
-#       participant \
-#       --participant-label ${subj_ID} \
-#       --skip-bids-validation \
-#       --md-only-boilerplate \
-#       --fs-license-file ${license} \
-#       --output-spaces ${FPREP_OUT_SPACES} \
-#       ${cifti_flag} \
-#       ${syn_flag} \
-#       ${config_flag} \
-#       ${task_flag} \
-#       --nthreads ${nthreads} \
-#       --stop-on-first-crash \
-#       -w ${work}
+    unset PYTHONPATH; singularity run --cleanenv -B ${binding}:${binding} ${fprep_container} \
+      ${project} ${derivatives} \
+      participant \
+      --participant-label ${subj_ID} \
+      --skip-bids-validation \
+      --md-only-boilerplate \
+      --fs-license-file ${license} \
+      --output-spaces ${FPREP_OUT_SPACES} \
+      ${cifti_flag} \
+      ${syn_flag} \
+      ${config_flag} \
+      ${task_flag} \
+      --nthreads ${nthreads} \
+      --stop-on-first-crash \
+      -w ${work}
 
-#   fi
+  fi
 
-# elif [[ ${system} == "local" ]]; then
+elif [[ ${system} == "local" ]]; then
 
-#   if [[ ${mode} == "anat" ]]; then
+  if [[ ${mode} == "anat" ]]; then
 
-#     echo "Running fMRIprep with --anat-only option locally"
-#     export PYTHONPATH=${FREESURFER_HOME}/python
-#     fmriprep ${project} ${derivatives} \
-#       participant \
-#       --participant-label ${subj_ID} \
-#       --skip-bids-validation \
-#       --md-only-boilerplate \
-#       --fs-license-file ${license} \
-#       --output-spaces ${FPREP_OUT_SPACES} \
-#       ${cifti_flag} \
-#       ${syn_flag} \
-#       --stop-on-first-crash \
-#       --anat-only \
-#       -w ${work}
+    echo "Running fMRIprep with --anat-only option locally"
+    export PYTHONPATH=${FREESURFER_HOME}/python
+    fmriprep ${project} ${derivatives} \
+      participant \
+      --participant-label ${subj_ID} \
+      --skip-bids-validation \
+      --md-only-boilerplate \
+      --fs-license-file ${license} \
+      --output-spaces ${FPREP_OUT_SPACES} \
+      ${cifti_flag} \
+      ${syn_flag} \
+      --stop-on-first-crash \
+      --anat-only \
+      -w ${work}
 
-#   else
+  else
 
-#     echo "Running full fMRIprep pipeline locally"
-#     export PYTHONPATH=${FREESURFER_HOME}/python
-#     fmriprep ${project} ${derivatives}/derivatives \
-#       participant \
-#       --participant-label ${subj_ID} \
-#       --skip-bids-validation \
-#       --md-only-boilerplate \
-#       --fs-license-file ${license} \
-#       --output-spaces ${FPREP_OUT_SPACES} \
-#       ${cifti_flag} \
-#       ${syn_flag} \      
-#       --stop-on-first-crash \
-#       -w ${work}
+    echo "Running full fMRIprep pipeline locally"
+    export PYTHONPATH=${FREESURFER_HOME}/python
+    fmriprep ${project} ${derivatives}/derivatives \
+      participant \
+      --participant-label ${subj_ID} \
+      --skip-bids-validation \
+      --md-only-boilerplate \
+      --fs-license-file ${license} \
+      --output-spaces ${FPREP_OUT_SPACES} \
+      ${cifti_flag} \
+      ${syn_flag} \      
+      --stop-on-first-crash \
+      -w ${work}
 
-#   fi
+  fi
 
-# else
+else
 
-#   echo "ERROR in `basename ${0}`: Unknown option ${system}. Please specify \"anat\" or leave empty for anat+func"
+  echo "ERROR in `basename ${0}`: Unknown option ${system}. Please specify \"anat\" or leave empty for anat+func"
 
-# fi
+fi
 
 # fMRIPrep's boldref seems to be messy lately (snow-like noise pattern instead of an image)
 bold_files=`find ${derivatives}/fmriprep/*${subj_ID}/ -type f -name "*preproc_bold.nii.gz" 2>/dev/null`
