clean up

diff --git a/bin/call_fmriprep b/bin/call_fmriprep
--- a/bin/call_fmriprep
+++ b/bin/call_fmriprep
@@ -243,7 +243,7 @@ if [[ ${WARP_ONLY} -eq 0 ]]; then
     fi
 
     # define SGE command
-    run_cmd="unset PYTHONPATH; singularity run --cleanenv -B ${binding}:${binding} ${fprep_container}"
+    run_cmd="singularity run --cleanenv -B ${binding}:${binding} ${fprep_container}"
 
   elif [[ ${system} == "local" ]]; then
     run_cmd="fmriprep"
@@ -275,6 +275,13 @@ if [[ ${WARP_ONLY} -eq 0 ]]; then
     ${nthread_flag} \
     --stop-on-first-crash \
     -w ${work}
+
+  if [[ $? != 0 ]]; then
+    echo
+    echo "---------------------------------------------------------------------------------------------------"
+    echo "ERROR in `basename ${0}`: job submission/execution was unsuccessful"
+    exit 1
+  fi    
 
 else
   echo "Skipping fMRIPrep, continuing to \"boldref\" and \"bold-to-T1w\" files"
