indentation

diff --git a/bin/call_cat12 b/bin/call_cat12
--- a/bin/call_cat12
+++ b/bin/call_cat12
@@ -96,8 +96,8 @@ if [[ -z ${MODE} ]]; then
   MODE='brain'
 else
   if [[ ${MODE,,} != 'full' && ${MODE,,} != 'brain' ]]; then
-      echo "ERROR in `basename ${0}`: MODE must be \"full\" or \"brain\", got \"${MODE}\""
-      exit 1
+    echo "ERROR in `basename ${0}`: MODE must be \"full\" or \"brain\", got \"${MODE}\""
+    exit 1
   fi
 fi
 
