fix call to registration script

diff --git a/bin/call_antsregistration b/bin/call_antsregistration
--- a/bin/call_antsregistration
+++ b/bin/call_antsregistration
@@ -296,7 +296,7 @@ if [[ $? -ne 0 ]]; then
   exit 1
 fi
 
-if [[ $# -lt 4 ]] ; then
+if [[ $# -lt 3 ]] ; then
   echo "NOT ENOUGH ARGUMENTS SPECIFIED"
   Usage >&2
   exit 1
@@ -441,7 +441,7 @@ if [[ ${TYPE,,} == "rigid" ]]; then
 elif [[ ${TYPE,,} == "affine" ]]; then
   cmd="""antsRegistration ${VERBOSE} -d 3 --float 1 -z 1 ${INITIAL} --interpolation ${INT} ${MASK} --output [${OUT}] --use-histogram-matching ${use_hist} ${winsorize_flag} --transform Rigid[${gradient_step}] --metric ${metric}[${FIXED},${MOVING},1,${val},Regular,0.25] --convergence [${converg},1e-6,10] --shrink-factors ${shrink} --smoothing-sigmas ${smooth}vox --transform Affine[${gradient_step}] --metric ${metric}[$1,${MOVING},1,${val},Regular,0.25] --convergence [${converg},1e-6,10] --shrink-factors ${shrink} --smoothing-sigmas ${smooth}vox --collapse-output-transforms ${collapse_output}"""
 elif [[ ${TYPE,,} == "syn" ]]; then
-  cmd="""antsRegistration ${VERBOSE} -d 3 --float 1 -z 1 ${INITIAL} --interpolation ${INT} ${MASK} --output [${OUT}]  --use-histogram-matching ${use_hist} ${winsorize_flag} --transform Rigid[${gradient_step}] --metric ${metric}[${FIXED},${MOVING},1,${val},Regular,0.25] --convergence [${converg},1e-6,10] --shrink-factors ${shrink} --smoothing-sigmas ${smooth}vox --transform Affine[${gradient_step}] --convergence [${converg},1e-6,10] --shrink-factors ${shrink} --smoothing-sigmas ${smooth}vox --collapse-output-transforms ${collapse_output}"""
+  cmd="""antsRegistration ${VERBOSE} -d 3 --float 1 -z 1 ${INITIAL} --interpolation ${INT} ${MASK} --output [${OUT}]  --use-histogram-matching ${use_hist} ${winsorize_flag} --transform Rigid[${gradient_step}] --metric ${metric}[${FIXED},${MOVING},1,${val},Regular,0.25] --convergence [${converg},1e-6,10] --shrink-factors ${shrink} --smoothing-sigmas ${smooth}vox --transform Affine[${gradient_step}] --convergence [${converg},1e-6,10] --shrink-factors ${shrink} --smoothing-sigmas ${smooth}vox --transform SyN[${gradient_step},2,0] --metric CC[${FIXED},${MOVING},1,${val}] --convergence [${converg},1e-6,10] --shrink-factors ${shrink} --smoothing-sigmas ${smooth}vox --collapse-output-transforms ${collapse_output}"""
 else
   echo "Unknown registration type \"${TYPE}\" specified"
   Usage >&2
@@ -462,6 +462,13 @@ echo ${cmd} >> ${OUT}command.txt
 
 # Execute command
 ${cmd}
+
+if [[ $? -ne 0 ]]; then
+  echo
+  echo "---------------------------------------------------------------------------------------------------"
+  echo "ERROR in `basename ${0}`: antsRegistration exited with non-zero status.."
+  exit 1
+fi
 
 # rename
 if [[ -f ${OUT}0GenericAffine.mat ]]; then
diff --git a/shell/spinoza_registration b/shell/spinoza_registration
--- a/shell/spinoza_registration
+++ b/shell/spinoza_registration
@@ -72,6 +72,7 @@ fi
 SGE=0
 OW=
 reg_type=""
+verb_flag=""
 # Check for subject flag
 while getopts :-:ocs:n: argument
 do
@@ -89,7 +90,10 @@ do
           ;;  
         sge)
           SGE=1
-          ;;            
+          ;;    
+        verbose)
+          verb_flag="--verbose"
+          ;;                  
         *)
           if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then
             echo "Unknown option --${OPTARG}"
@@ -215,6 +219,7 @@ for subID in ${search}; do
   outWarp=${output_dir}/${base}_${ext}_mode-image_warp.nii.gz
   outInvWarp=${output_dir}/${base}_${ext}_mode-image_invwarp.nii.gz
   outGenAff=${output_dir}/${base}_${ext}_mode-image_xfm.mat
+  cmd_file=${output_dir}/${base}_${ext}_mode-image_cmd.txt
 
   if [[ ! -d ${output_dir} ]]; then
     echo "Creating output directory"
@@ -245,8 +250,8 @@ for subID in ${search}; do
           job="call_antsregistration"
         fi
 
-        echo "Registering $(basename ${moving}) to $(basename ${fixed}) [${type_reg^^}]"
-        ${job} ${reg_type} ${fixed} ${moving} ${output_dir}/${base}_${ext}
+        echo "Registering $(basename ${moving}) to $(basename ${fixed}) [${reg_type}]"
+        ${job} ${verb_flag} ${reg_type} ${fixed} ${moving} ${output_dir}/${base}_${ext}
 
         if [[ ${SGE} -eq 1 ]]; then
           echo "Waiting to check qstat.."
@@ -257,13 +262,11 @@ for subID in ${search}; do
             echo "ERROR in `basename ${0}`: wait_for_qsub exited with non-zero status"
             exit 1
           fi
-        fi
-
-        if [[ $? != 0 ]]; then
-          echo
-          echo "---------------------------------------------------------------------------------------------------"
-          echo "ERROR in `basename ${0}`: call_antsregistration exited with non-zero status"
-          exit 1
+        else
+          if [[ $? -ne 0 ]]; then
+            echo "ERROR in `basename ${0}`: call_antsregistration exited with non-zero status"
+            exit 1
+          fi
         fi
 
         if [[ ${type_reg} == "syn" ]]; then
@@ -273,6 +276,7 @@ for subID in ${search}; do
 
         # we'll have this file regardless of registration type
         mv ${output_dir}/${base}_${ext}genaff.mat ${outGenAff} 2>/dev/null
+        mv ${output_dir}/${base}_${ext}command.txt ${cmd_file} 2>/dev/null
 
       else
         echo "Renaming \"${base}_${ext}genaff.mat\" to \"`basename ${outGenAff}`\""
