support for new options

diff --git a/shell/master b/shell/master
--- a/shell/master
+++ b/shell/master
@@ -76,6 +76,7 @@ boldref_flag=""           # spinoza_fmriprep
 clean_flag=""             # spinoza_fmriprep
 fetch_fsl_flag=""         # spinoza_fmriprep
 fetch_func_flag=""        # spinoza_fmriprep
+mask_flag=""              # spinoza_fmriprep
 fetch_anat_flag=""        # spinoza_fmriprep
 DOCKER_FLAG=""            # spinoza_fmriprep
 WORK_FLAG=""              # spinoza_fmriprep
@@ -109,7 +110,7 @@ t_specified=0             # keep track when t-flag is specified or --func is use
 
 # use long options in bash:
 # https://stackoverflow.com/questions/402377/using-getopts-to-process-long-and-short-command-line-options
-declare -a array=("--no_bbr" "--local" "--ups" "--biascorr" "--remove_wf" "--remove_surf_wf" "--sge" "--no_freeview" "--comb_only" "--grid" "--multi_design" "--hrf" "--rigid" "--syn" "--affine" "--lines" "--gdh" "--nighres" "--surface" "--warp_only" "--no_raw" "--verbose" "--zcore" "--full" "--no_clip" "--tc" "--bgfs" "--inv" "--no_fit" "--fmriprep" "--fprep" "--v1" "--v2" "--save_grid" "--debug" "--no_nordic" "--ow" "--no_bounds" "--no_tsnr" "--mag" "--no_highres" "--xopts-use" "--xopts-clean" "--xopts-overwrite" "--take-avg-tr" "--force_exec" "--no_t2" "--merge_ses" "--fsaverage" "--fsnative" "--ap" "--pa" "--lr" "--rl" "--no_lpi" "--anat_only" "--func_only" "--no_boldref" "--gauss" "--dog" "--css" "--norm" "--no_srf" "--srf_file" "--gallery" "--abc" "--abd" "--manual" "--ctx" "--func" "--help" "--ofsl" "--clean" "--fd" "--fetch_fsl" "--anat" "--no_epi" "--no_manual" "--aparc" "--phys" "--skip_bg" "--docker" "--rh" "--lh" "--identity" "--ident" "--dcm_fix" "--try" "--fetch_anat" "--fetch_func" "--post_only" "--pre_only" "--pyb_only")
+declare -a array=("--no_bbr" "--local" "--ups" "--biascorr" "--remove_wf" "--remove_surf_wf" "--sge" "--no_freeview" "--comb_only" "--grid" "--multi_design" "--hrf" "--rigid" "--syn" "--affine" "--lines" "--gdh" "--nighres" "--surface" "--warp_only" "--no_raw" "--verbose" "--zcore" "--full" "--no_clip" "--tc" "--bgfs" "--inv" "--no_fit" "--fmriprep" "--fprep" "--v1" "--v2" "--save_grid" "--debug" "--no_nordic" "--ow" "--no_bounds" "--no_tsnr" "--mag" "--no_highres" "--xopts-use" "--xopts-clean" "--xopts-overwrite" "--take-avg-tr" "--force_exec" "--no_t2" "--merge_ses" "--fsaverage" "--fsnative" "--ap" "--pa" "--lr" "--rl" "--no_lpi" "--anat_only" "--func_only" "--no_boldref" "--gauss" "--dog" "--css" "--norm" "--no_srf" "--srf_file" "--gallery" "--abc" "--abd" "--manual" "--ctx" "--func" "--help" "--ofsl" "--clean" "--fd" "--fetch_fsl" "--anat" "--no_epi" "--no_manual" "--aparc" "--phys" "--skip_bg" "--docker" "--rh" "--lh" "--identity" "--ident" "--dcm_fix" "--try" "--fetch_anat" "--fetch_func" "--post_only" "--pre_only" "--pyb_only" "--masks" "--mask")
 
 # sort options array
 IFS=$'\n' opts=($(sort <<<"${array[*]}"))
@@ -412,7 +413,13 @@ do
           ;;
         pyb_only)
           pyb_flag="--pyb_only"
-          ;;                         
+          ;;       
+        masks)
+          mask_flag="--masks"
+          ;;                 
+        mask)
+          mask_flag="--masks"
+          ;;                                            
         dcm_fix)
           echo "This functionality is now default and therefore the flag is deprecated"
           exit 1
@@ -590,6 +597,14 @@ Arguments:
                     model. Should/can be use for module 17, pRF-fitting
   -x <kwargs>       Can be used for a variety of options by setting it to ANYTHING other than empty. 
                     Usages include:
+                      - spinoza_lsprep; Additional commands to be passed to 'call_lsprep'. Format should
+                        be comma-separated flags as follows: 
+                          - if you specify a flag and values | <flag>=<value>
+                          - if you specify a flag only | <flag>
+
+                        combine as:
+                        "-x <flag1>=<value>,<flag2>,<flag3>,<flag4>=<value>"
+
                       - spinoza_profiling; specify the type of file to use
                       - spinoza_fitprfs; specify the constraints to use for fitting. Should be format-
                         ted as -x "<gaussian>,<extended>". E.g., '-x tc,bgfs'
@@ -665,6 +680,8 @@ Arguments:
   --lh              use left hemisphere for spinoza_lineplanning (same as '-h left')
   --merge_ses       average pRF data from all sessions
   --mag             use magnitude only for NORDIC denoising (spinoza_nordic)
+  --masks           used in combination with '--fetch_{fsl|func|anat}' to also fetch the brain masks
+                    associated with the timeseries files  
   --multi_design    specifies that for all runs in the dataset have run-/task-specific screenshot di-
                     rectories. This requires that the directory names you saved must match your naming 
                     scheme of functional files as we'll match on run-/task-ID (spinoza_fitprfs)
@@ -699,6 +716,10 @@ Arguments:
                     scanner2bids). Useful for adhoc conversion of physiology data. Files ending with
                     ".log", and containing "SCANPHYS" and "bold" must be placed somewhere in the DIR-
                     DATA_SOURCE/<subject>/<ses> folder. 
+  --pre_only        spinoza_denoising; only run the step that saves the standard deviation/mean 
+  --pyb_only        spinoza_denoising; only run the the pybest step; pretty much equivalent to '--no_raw'
+  --post_only       spinoza_denoising; only run the step that performs the unzscoring; assumes pybest 
+                    was already run
   --ups             maps to '-u' in spinoza_qmrimaps; turn on Universal Pulses
   --remove_wf       remove full single_subject workflow folder. Use \"--remove_surf_wf\"to specifically 
                     remove the surface reconstruction folder when you have new FreeSurfer output that 
@@ -821,10 +842,6 @@ if [[ ! -z ${WHICH_MOD} ]] && [[ "${@}" != *"-m"* ]]; then
     echo "could not find a module associated with \"${WHICH_MOD}\""
   fi
 fi
-
-#---------------------------------------------------------------------------------------------------------
-# source setup
-call_loadsetup
 
 #---------------------------------------------------------------------------------------------------
 # Define default session/subject stuff
@@ -1032,8 +1049,8 @@ if [[ $? -eq 0 ]]; then
 fi
 
 #---------------------------------------------------------------------------------------------------
-# STEP 03: Reconstruct line-data (scripts Luisa)
-module=03
+# STEP 03a: Reconstruct line-data (scripts Luisa)
+module="03a"
 
 # Check whether the module should be executed
 echo ${FLAG_executeModule} | grep -q ${module}
@@ -1061,8 +1078,54 @@ if [[ $? -eq 0 ]]; then
     ${DEBUG} \
     ${OW} \
     ${SGE} \
+    ${SGE_QUEUE} \
     ${NORDIC} \
     ${DIR_DATA_HOME} ${DIR_DATA_SOURCE}
+
+  if [[ $? -ne 0 ]]; then
+    echo "ERROR in master: spinoza_linerecon exited with non-zero status"
+    exit 1
+  fi
+
+  echo "[${module}] DONE" && echo
+
+fi
+
+#---------------------------------------------------------------------------------------------------
+# STEP 03b: LSprep | basic quality control and parsing into h5-file
+module="03b"
+
+# Check whether the module should be executed
+echo ${FLAG_executeModule} | grep -q ${module}
+
+if [[ $? -eq 0 ]]; then
+
+  if [[ ${HELP} -eq 1 ]]; then
+    ${job} spinoza_linerecon
+    exit 1
+  fi
+
+  echo "---------------------------------------------------------------------------------------------------"
+  echo "[${module}] LSprep | basic quality control"
+
+  if [[ -z ${SES} ]]; then
+    # Going to assume ses-1 here
+    SESSION="-n 2"
+  fi
+
+  # check for lsprep kwargs
+  KWARGS_FLAG=""
+  if [[ ! -z ${KWARGS} ]]; then
+    KWARGS_FLAG="-x ${KWARGS}"
+  fi
+
+  ${job} spinoza_lsprep \
+    ${SUBJECT} \
+    ${SESSION} \
+    ${SGE} \
+    ${SGE_QUEUE} \
+    ${KWARGS_FLAG} \
+    ${DIR_DATA_HOME} ${DIR_DATA_DERIV}
 
   if [[ $? -ne 0 ]]; then
     echo "ERROR in master: spinoza_linerecon exited with non-zero status"
@@ -1604,6 +1667,7 @@ if [[ $? -eq 0 ]]; then
     ${fetch_fsl_flag} \
     ${fetch_func_flag} \
     ${fetch_anat_flag} \
+    ${mask_flag} \
     ${WORK_FLAG} \
     ${CRASH_FLAG} \
     -f ${DIR_DATA_HOME} \
