various

diff --git a/shell/master b/shell/master
--- a/shell/master
+++ b/shell/master
@@ -34,6 +34,7 @@ GALLERY_FLAG=""           # spinoza_bestvertex
 MAN_EPI=""                # spinoza_bestvertex
 EPI_FILE=""               # spinoza_bestvertex
 LS_SES=""                 # spinoza_bestvertex
+skip_prf_info=""          # spinoza_bestvertex
 PROC=""                   # spinoza_brainextraction
 SELECTION_FLAG=""         # spinoza_bestvertex
 OPEN_WITH_FLAG=""         # spinoza_bestvertex
@@ -42,6 +43,7 @@ post_flag=""              # spinoza_denoising
 pyb_flag=""               # spinoza_denoising
 raw_flag=""               # spinoza_denoising
 SGE=""                    # spinoza_denoising/spinoza_nordic/spinoza_linerecon/spinoza_registration
+cmd_flag=""               # spinoza_registration
 COMB_ONLY=""              # spinoza_extractregions
 CLIP=""                   # spinoza_fitprfs
 CLIP_FLAG=""              # spinoza_fitprfs
@@ -62,6 +64,10 @@ bouds_flag=""             # spinoza_fitprfs
 merge_flag=""             # spinoza_fitprfs
 jobs_flag=""              # spinoza_fitprfs
 MODEL_FLAG="--gauss"      # spinoza_fitprfs
+REFIT_FLAG=""             # spinoza_fitprfs
+PIXEL_FLAG=""             # spinoza_fitprfs
+BOLD_FLAG=""              # spinoza_fitprfs
+FOLDS_FLAG=""             # spinoza_fitprfs
 highres_flag=""           # spinoza_freesurfer
 XOPTS_=""                 # spinoza_freesurfer
 expert_flag=""            # spinoza_freesurfer
@@ -110,13 +116,13 @@ t_specified=0             # keep track when t-flag is specified or --func is use
 
 # use long options in bash:
 # https://stackoverflow.com/questions/402377/using-getopts-to-process-long-and-short-command-line-options
-declare -a array=("--no_bbr" "--local" "--ups" "--biascorr" "--remove_wf" "--remove_surf_wf" "--sge" "--no_freeview" "--comb_only" "--grid" "--multi_design" "--hrf" "--rigid" "--syn" "--affine" "--lines" "--gdh" "--nighres" "--surface" "--warp_only" "--no_raw" "--verbose" "--zcore" "--full" "--no_clip" "--tc" "--bgfs" "--inv" "--no_fit" "--fmriprep" "--fprep" "--v1" "--v2" "--save_grid" "--debug" "--no_nordic" "--ow" "--no_bounds" "--no_tsnr" "--mag" "--no_highres" "--xopts-use" "--xopts-clean" "--xopts-overwrite" "--take-avg-tr" "--force_exec" "--no_t2" "--merge_ses" "--fsaverage" "--fsnative" "--ap" "--pa" "--lr" "--rl" "--no_lpi" "--anat_only" "--func_only" "--no_boldref" "--gauss" "--dog" "--css" "--norm" "--no_srf" "--srf_file" "--gallery" "--abc" "--abd" "--manual" "--ctx" "--func" "--help" "--ofsl" "--clean" "--fd" "--fetch_fsl" "--anat" "--no_epi" "--no_manual" "--aparc" "--phys" "--skip_bg" "--docker" "--rh" "--lh" "--identity" "--ident" "--dcm_fix" "--try" "--fetch_anat" "--fetch_func" "--post_only" "--pre_only" "--pyb_only" "--masks" "--mask")
+declare -a array=("--no_bbr" "--local" "--ups" "--biascorr" "--remove_wf" "--remove_surf_wf" "--sge" "--no_freeview" "--comb_only" "--grid" "--multi_design" "--hrf" "--rigid" "--syn" "--affine" "--lines" "--gdh" "--nighres" "--surface" "--warp_only" "--no_raw" "--verbose" "--zcore" "--full" "--no_clip" "--tc" "--bgfs" "--inv" "--no_fit" "--fmriprep" "--fprep" "--v1" "--v2" "--save_grid" "--debug" "--no_nordic" "--ow" "--no_bounds" "--no_tsnr" "--mag" "--no_highres" "--xopts-use" "--xopts-clean" "--xopts-overwrite" "--take-avg-tr" "--force_exec" "--no_t2" "--merge_ses" "--fsaverage" "--fsnative" "--ap" "--pa" "--lr" "--rl" "--no_lpi" "--anat_only" "--func_only" "--no_boldref" "--gauss" "--dog" "--css" "--norm" "--no_srf" "--srf_file" "--gallery" "--abc" "--abd" "--manual" "--ctx" "--func" "--help" "--ofsl" "--clean" "--fd" "--fetch_fsl" "--anat" "--no_epi" "--no_manual" "--aparc" "--phys" "--skip_bg" "--docker" "--rh" "--lh" "--identity" "--ident" "--dcm_fix" "--try" "--fetch_anat" "--fetch_func" "--post_only" "--pre_only" "--pyb_only" "--masks" "--mask" "--skip_prf_info" "--refit" "--separate_hrf" "--bold" "--cmd")
 
 # sort options array
 IFS=$'\n' opts=($(sort <<<"${array[*]}"))
 unset IFS
 
-while getopts :-:ofm:s:h:n:t:l:v:p:x:u:r:e:i:c:k:j:q:a:d:w: arg
+while getopts :-:om:f:s:h:n:t:l:v:p:x:u:r:e:i:c:k:j:q:a:d:w: arg
 do
   case ${arg} in
     -)
@@ -179,9 +185,12 @@ do
         multi_design)
           MULTIPLE_DESIGNS="--multi_design"
           ;;   
-        hrf)
-          FIT_HRF="--hrf"
+        no_hrf)
+          FIT_HRF="--no_hrf"
           ;;
+        separate_hrf)
+          FIT_HRF="--separate_hrf"
+          ;;          
         rigid)
           REG_TYPE="--rigid"
           ;;
@@ -419,7 +428,19 @@ do
           ;;                 
         mask)
           mask_flag="--masks"
-          ;;                                            
+          ;;   
+        skip_prf_info)
+          skip_prf_info="--skip_prf_info"
+          ;;
+        refit)
+          REFIT_FLAG="--refit"
+          ;;          
+        bold)
+          BOLD_FLAG="--bold"
+          ;;             
+        cmd)
+          cmd_flag="--cmd"
+          ;;             
         dcm_fix)
           echo "This functionality is now default and therefore the flag is deprecated"
           exit 1
@@ -471,6 +492,7 @@ do
     e)  n_echoes=${OPTARG}
         START_STAGE=${OPTARG}
         EPI_FILE="-e ${OPTARG}"
+        PIXEL_FLAG="-p ${OPTARG}"
           ;;
     i)  images=${OPTARG}
           ;;
@@ -482,7 +504,7 @@ do
           ;;          
     j)  jobs_flag="-j ${OPTARG}"
           ;;          
-    f)  FULL_OW="--full"
+    f)  FOLDS_FLAG="-f ${OPTARG}"
           ;;          
     k)  kwargs_file="-k `readlink -f ${OPTARG}`"
           ;;     
@@ -538,13 +560,18 @@ Arguments:
                         one of 'pial' (for pial edits), 'wm' (for white matter edits), or 'cp' if
                         you added control points. See 'call_freesurfer' for more information
                       - spinoza_bestvertex; specify manual EPI-file
+                      - spinoza_fitprfs: set the number of pixels (default = 100)
   -h <hemisphere>   used for lineplanning, denotes which hemisphere to process
+  -f <n_folds>      if your pRF experiment contains multiple equal sequences, you can use this flag
+                    to perform within-run averaging before percent-changing in call_prf. This should
+                    be in concert with number of volumes removed from the beginning of the timeseries
   -i <image path>   specify custom path to:
                       - spinoza_fitprfs: PNG's for pRF-fitting. This allows deviation from the stan-
                         dard path that 'spinoza_fitprfs' will be looking for
                       - spinoza_denoising: input directory for pybest. By default 'fmriprep', but 
                         can be something else
-                      - spinoza_lineplanning: file to use for registration with ses-1 (default to DIR_DATA_SOURCE/<subject>/ses-<ls_session>/planning)
+                      - spinoza_lineplanning: file to use for registration with ses-1 (default to 
+                        DIR_DATA_SOURCE/<subject>/ses-<ls_session>/planning)
   -j <n_jobs>       number of jobs to use when submitting to SoGE. Used in:
                       - spinoza_mriqc
                       - spinoza_freesurfer
@@ -623,6 +650,7 @@ Arguments:
                     recommended to at least to Gaussian fitting with trust-constr, and potential ex-
                     tended models with L-BGFS. For this, see '-x' flag
   --biascorr        don't perform bias correction after denoising (spinoza_biassanlm)
+  --bold            re-calculate the BOLD timecourses; otherwise use existing '*hemi-LR_desc-avg_bold.npy'   
   --clean           remove the single-subject workflow folder completely. This saves storage, but comes
                     at the price that it re-runs EVERYTHING if you restart the process.                    
   --comb_only       skip nighres, only do combination of segmentations. Works with '-o' flag.
@@ -720,7 +748,6 @@ Arguments:
   --pyb_only        spinoza_denoising; only run the the pybest step; pretty much equivalent to '--no_raw'
   --post_only       spinoza_denoising; only run the step that performs the unzscoring; assumes pybest 
                     was already run
-  --ups             maps to '-u' in spinoza_qmrimaps; turn on Universal Pulses
   --remove_wf       remove full single_subject workflow folder. Use \"--remove_surf_wf\"to specifically 
                     remove the surface reconstruction folder when you have new FreeSurfer output that 
                     fMRIPrep needs to use, or "--ow" to remove all folders within single_subj workflow
@@ -730,6 +757,8 @@ Arguments:
   --rh              use right hemisphere for spinoza_lineplanning (same as '-h right')             
   --rigid           use 'rigid-body' registration (spinoza_registration)
   --save_grid       Save out gridsearch parameters (default skips saving grid-parameters)
+  --separate_hrf    Fit the HRF in two stages; can sometimes avoid sending the optimizer into the forrest
+                    but comes at a computational cost
   --sge             passes '--sge' on to:
                       -spinoza_scanner2bids
                       -spinoza_linerecon
@@ -737,6 +766,10 @@ Arguments:
                       -spinoza_nordic
                       -spinoza_registration
                     submits jobs to cluster
+  --skip_prf_info   skip the creation of the 'model-{}_desc-best_vertices.csv'. This can be useful if 
+                    you want an indication of the pRF-properties, but want to refit yourself. This is 
+                    the case where I use M. Aqil's fitting output, which has been fitted with an out-
+                    dated screen distance.    
   --srf_file        search for file with SRFs (should be call "desc-srfs_centered.csv" in the subjects'
                     pRF folder, e.g., 'derivatives/prf/<subject>/ses-<x>/sub-001_desc-srfs_centered.csv').
                     Values representing suppression strength will be included when selecting the best 
@@ -749,6 +782,7 @@ Arguments:
                     (e.g., DoG, CSS, or DN). By default, we'll use trust-constr minimization for both. 
                     It's recommended to at least to Gaussian fitting with trust-constr, and potential 
                     extended models with L-BGFS. For this, see '-x' flag 
+  --ups             maps to '-u' in spinoza_qmrimaps; turn on Universal Pulses
   --v1              only fit voxels from ?.V1_exvivo.thresh.label; the original dimensions will be 
                     maintained, but timecourses outside of the ROI are set to zero
   --v2              only fit voxels from ?.V2_exvivo.thresh.label; the original dimensions will be 
@@ -1210,6 +1244,7 @@ if [[ $? -eq 0 ]]; then
     ${SGE_QUEUE} \
     ${FSL_FLAG} \
     ${jobs_flag} \
+    ${cmd_flag} \
     ${INPUT_DIR} ${DIR_DATA_DERIV}/ants
 
   if [[ $? -ne 0 ]]; then
@@ -1251,6 +1286,7 @@ if [[ $? -eq 0 ]]; then
     ${SGE_QUEUE} \
     ${FSL_FLAG} \
     ${jobs_flag} \
+    ${cmd_flag} \
     ${INPUT_DIR} ${DIR_DATA_DERIV}/ants mni
 
   if [[ $? -ne 0 ]]; then
@@ -1820,6 +1856,10 @@ if [[ $? -eq 0 ]]; then
     ${space_flag} \
     ${SGE_QUEUE} \
     ${SET_TR} \
+    ${PIXEL_FLAG} \
+    ${REFIT_FLAG} \
+    ${FOLDS_FLAG} \
+    ${BOLD_FLAG} \
     ${PRF_INPUT} ${DIR_DATA_DERIV}/prf ${PNG_DIR}
 
   if [[ $? -ne 0 ]]; then
@@ -1883,6 +1923,7 @@ if [[ $? -eq 0 ]]; then
     ${MAN_EPI} \
     ${EPI_FILE} \
     ${LS_SES} \
+    ${skip_prf_info} \
     ${DIR_DATA_HOME} ${DIR_DATA_DERIV} ${LABEL_FILE}
 
   if [[ $? -ne 0 ]]; then
@@ -2167,6 +2208,42 @@ if [[ $? -eq 0 ]]; then
 
   if [[ $? -ne 0 ]]; then
     echo "ERROR in master: spinoza_segmentsubcortex exited with non-zero status"
+    exit 1
+  fi
+
+  echo "[${module}] DONE" && echo
+
+fi
+
+#---------------------------------------------------------------------------------------------------
+# STEP 27: Project line to surface with a registration cascade
+module=27
+
+# Check whether the module should be executed
+echo ${FLAG_executeModule} | grep -q ${module}
+
+if [[ $? -eq 0 ]]; then
+
+  if [[ ${HELP} -eq 1 ]]; then
+    ${job} spinoza_suit
+    exit 1
+  fi
+
+  echo "---------------------------------------------------------------------------------------------------"
+  echo "[${module}] Cerebellum segmentation with SUIT"
+
+  # check where inputs live
+  INPUT_DIR=`find_hierarchical_anatomy 6`
+
+  # spinoza_profiling ${SUBJECT} ${SESSION} ${OW} ${DIR_DATA_DERIV}/nighres ${DIR_DATA_HOME} T1map
+  ${job} spinoza_suit \
+    ${SUBJECT} \
+    ${SESSION} \
+    ${OW} \
+    ${INPUT_DIR} ${DIR_DATA_DERIV}/suit
+
+  if [[ $? -ne 0 ]]; then
+    echo "ERROR in master: spinoza_suit exited with non-zero status"
     exit 1
   fi
 
